# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # üá´üá∑ La langue qui n'aura PAS de pr√©fixe dans l'URL (ex: /accueil)
    app.default_locale: 'us'

    # üåê Toutes les locales support√©es (format requis pour le "requirements" des routes)
    app.locales: 'fr|us|es'

    # üíª Liste des locales sous forme de tableau (utile pour PHP et Twig)
    app.locales_array: ['fr', 'us', 'es']

    app.square_access_token: '%env(SQUARE_ACCESS_TOKEN)%'
    app.square_use_sandbox: '%env(bool:SQUARE_USE_SANDBOX)%'
    # Ajoutons les autres pour la coh√©rence
    app.square_currency: '%env(SQUARE_CURRENCY)%'
    app.square_application_id: '%env(SQUARE_APPLICATION_ID)%'
    app.square_location_id: '%env(SQUARE_LOCATION_ID)%'
    app.square_tax_id: '%env(SQUARE_TAX_ID)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.




    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Configuration manuelle de l'Event Subscriber (LocaleSubscriber) pour injecter les param√®tres
    App\EventSubscriber\LocaleSubscriber:
        arguments:
            $defaultLocale: '%app.default_locale%'
            $supportedLocales: '%app.locales_array%'

